const message = {
    INTERNAL_SERVER_ERROR: 'something went wrong',
    REQUEST_SUCCESSFUL: 'request successful',
    ID_NOT_FOUND: 'document id not found',
    INVALID_REQUEST_ID: 'request id is invalid',
    CREATED_SUCCESSFULLY: 'data created successfully',
    UPDATED_SUCCESSFULLY: 'data updated successfully',
    DELETED_SUCCESSFULLY: 'data deleted successfully',

    // careerpath messages
    CAREER_PATH_ID_REQUIRED: 'careerpath id is required',
    CAREER_PATH_TITLE_REQUIRED: 'careerpath title is required',
    CAREER_PATH_ID_INVALID: 'careerpath id is invalid',
    CAREER_PATH_TITLE_CHARS_LIMIT_EXCEEDED: 'careerpath title characters limit are exceeded',
    CAREER_PATH_DESCRIPTION_REQUIRED: 'careerpath description is required',
    CAREER_PATH_IMAGE_REQUIRED: 'careerpath image is required',
    CAREER_PATH_BEST_FOR_REQUIRED: 'careerpath best_for is required',
    CAREER_PATH_BEST_FOR_INVALID_VALUE: 'careerpath best_for value is invalid',
    CAREER_PATH_PERSONALITY_TYPE_REQUIRED: 'careerpath personality_type is required',
    CAREER_PATH_PERSONALITY_TYPE_INVALID_VALUE: 'careerpath personality_type value is invalid',

    // course flow type messages
    COURSE_FLOW_TYPE_ID_REQUIRED: 'course flow type id is required',
    COURSE_FLOW_TYPE_ID_INVALID: 'course flow type id is invalid',
    COURSE_FLOW_TYPE_NAME_REQUIRED: 'course flow type name is required',
    COURSE_FLOW_TYPE_NAME_CHARS_LIMIT_EXCEEDED: 'course flow type name characters limit are exceeded',
    COURSE_FLOW_TYPE_DESCRIPTION_REQUIRED: 'course flow type description is required',

    // personality type messages
    PERSONALITY_TYPE_ID_REQUIRED: 'personality type id is required',
    PERSONALITY_TYPE_ID_INVALID: 'personality type id is invalid',
    PERSONALITY_TYPE_NAME_REQUIRED: 'personality type name is required',
    PERSONALITY_TYPE_NAME_CHARS_LIMIT_EXCEEDED: 'personality type name characters limit are exceeded',
    PERSONALITY_TYPE_DESCRIPTION_REQUIRED: 'personality type description is required',

    // quiz messages
    QUIZ_ID_REQUIRED: 'quiz type id is required',
    QUIZ_ID_INVALID: 'quiz type id is invalid',
    QUIZ_TYPE_REQUIRED: 'quiz type is required',
    QUIZ_TYPE_INVALID: 'quiz type is invalid',
    QUIZ_TOTAL_QUESTIONS_REQUIRED: 'quiz total questions are required',
    QUIZ_TOTAL_QUESTIONS_INVALID: 'quiz total questions are invalid',
    QUIZ_NAME_REQUIRED: 'quiz name is required',
    QUIZ_DESCRIPTION_REQUIRED: 'quiz description is required',
    QUIZ_QUARKS_REQUIRED: 'quiz quarks are required',
    QUIZ_IMAGE_REQUIRED: 'quiz image is required',
    QUIZ_BACKGROUND_COLOR_REQUIRED: 'quiz background color is required',
    QUIZ_TEXT_COLOR_REQUIRED: 'quiz text color is required',
    QUIZ_CONTENT_REQUIRED: 'quiz content is required',
    QUIZ_CONTENT_INVALID: 'quiz content id is invalid',
    QUIZ_DURATION_REQUIRED: 'quiz duration is required',
    QUIZ_END_OF_WEEK_INVALID: 'quiz end of week value is invalid',

    // skill category messages
    SKILL_CATEGORY_ID_REQUIRED: 'skill category id is required',
    SKILL_CATEGORY_NAME_REQUIRED: 'skill category name is required',
    SKILL_CATEGORY_DESCRIPTION_REQUIRED: 'skill category description is required',
    SKILL_CATEGORY_CREATOR_ID_REQUIRED: 'skill category creator id is required',
    SKILL_CATEGORY_PUBLISH_STATUS_REQUIRED: 'skill category publish status is required',
    SKILL_CATEGORY_PUBLISH_STATUS_INVALID: 'skill category publish status is invalid',
    SKILL_CATEGORY_ID_INVALID: 'skill category id is invalid',

    // course messages
    COURSE_ID_REQUIRED: 'course id is required',
    COURSE_NAME_REQUIRED: 'course name is required',
    COURSE_FLOW_TYPE_ID_REQUIRED: 'course flow type id is required',
    COURSE_FLOW_TYPE_ID_INVALID: 'course flow type id is invalid',
    COURSE_PAID_REQUIRED: 'course paid is required',
    COURSE_PAID_INVALID: 'course paid is invalid',
    COURSE_SUB_TITLE_REQUIRED: 'course sub title is required',
    COURSE_PERSONALITY_TYPE_REQUIRED: 'course personality type is required',
    COURSE_PERSONALITY_TYPE_INVALID: 'course personality type is invalid',
    COURSE_DESCRIPTION_REQUIRED: 'course description is required',
    COURSE_IMAGE_REQUIRED: 'course image is required',
    COURSE_BACKGROUND_COLOR_REQUIRED: 'course background color is required',
    COURSE_TEXT_COLOR_REQUIRED: 'course text color is required',
    COURSE_RELATED_CAREER_REQUIRED: 'course related career is required',
    COURSE_RELATED_CAREER_INVALID: 'course related career is invalid',
    COURSE_TOTAL_TASK_REQUIRED: 'course total task is required',
    COURSE_SKILL_CATEGORY_REQUIRED: 'course skill category is required',
    SKILL_CATEGORIES_INVALID: 'skill categories field is invalid',

    // course task messages
    COURSE_TASK_ID_REQUIRED: 'course task id is required',
    COURSE_ID_REQUIRED: 'course id is required',
    COURSE_ID_INVALID: 'course id is invalid',
    COURSE_TASK_LEVEL_REQUIRED: 'course task level is required',
    COURSE_TASK_LEVEL_INVALID: 'course task level is invalid',
    COURSE_TASK_CONTENT_COUNT_REQUIRED: 'course task content count is required',
    COURSE_TASK_CONTENT_COUNT_ONLY_NUMBERS_ALLOWED: 'course task content count is numeric',
    COURSE_TASK_DURATION_REQUIRED: 'course task duration is required',
    COURSE_TASK_TOC_DATA_REQUIRED: 'course task toc data is required',
    COURSE_TASK_TOC_DATA_INVALID: 'course task toc data is invalid',
    COURSE_TASK_INSTREAM_CONTENT_REQUIRED: 'course task instream content is required',
    COURSE_TASK_INSTREAM_CONTENT_INVALID: 'course task instream content is invalid',

    COURSE_TOTAL_TASK_NUMBER: 'total task field type is number',
    QUARKS_REQUIRED: 'quarks field is required',
    QUARKS_TYPE_NUMBER: 'quarks field type is number',

    COURSE_TASK_TYPE_REQUIRED: 'course task type is required',
    COURSE_TASK_TYPE_INVALID: 'course task type is invalid',
    CAREER_PATH_ALREADY_EXISTS: 'career path already exists',
    CONTENT_ALREADY_EXISTS: 'content already exists',
    COURSE_FLOW_TYPE_ALREADY_EXISTS: 'course flow type already exists',
    COURSE_TASK_ALREADY_EXISTS: 'course task already exists',
    COURSE_ALREADY_EXISTS: 'course already exists',
    PERSONALITY_TYPE_ALREADY_EXISTS: 'personality type already exists',
    QUIZ_ALREADY_EXISTS: 'quiz already exists',
    SKILL_CATEGORY_ALREADY_EXISTS: 'skill category already exists',

    CONTENT_TITLE_REQUIRED: 'content title is required',
    CONTENT_REQUIRED: 'content is required',
    CONTENT_TYPE_REQUIRED: 'content type is required',
    CONTENT_TYPE_INVALID: 'content type is invalid',
    CONTENT_TEMPLATE_ID_REQUIRED: 'content template id is required',
    CONTENT_TEMPLATE_TYPE_REQUIRED: 'content template type is required',
    CONTENT_VIDEO_ID_REQUIRED: 'content video id is required',
    CONTENT_VIDEO_CREDIT_REQUIRED: 'content video credit is required',
    CONTENT_IMAGE_REQUIRED: 'content image is required',
    CONTENT_IMAGE_CREDIT_REQUIRED: 'content image credit is required',
    CONTENT_CREATOR_ID_REQUIRED: 'content creator id is required',
    CONTENT_PUBLISH_STATUS_REQUIRED: 'content publish status is required',
    CONTENT_PUBLISH_STATUS_INVALID: 'content publish status is invalid',
    CONTENT_OPTION_REQUIRED: 'content option is required',
    CONTENT_OPTION_INVALID: 'content option is invalid',
    CONTENT_OPTION_OUTCOME_ID_INVALID: 'outcome content id is invalid',
    OUTCOME_CONTENT_ID_REQUIRED: 'outcome content id is required',
    INSTREAM_CONTENT_ID_REQUIRED: 'instream content id is required',
    INSTREAM_CONTENT_ID_INVALID: 'instream content id is invalid',
    INSTREAM_QUIZ_REQUIRED: 'instream quiz is required',
    INSTREAM_QUIZ_INVALID: 'instream quiz is invalid',
    CONTENT_COVER_DATA_REQUIRED: 'content cover data is required',
    CONTENT_COVER_DATA_INVALID: 'content cover data is invalid',

    INSTREAM_CONTENT_REQUIRED: 'instream content is required',
    INSTREAM_CONTENT_INVALID: 'instream content is invalid',
    INSTREAM_CONTENT_ID_INVALID: 'instream content id is invalid',

    TAG_NOT_EXIST: 'tag not found',
    TAG_ID_REQUIRED: 'tag id is required',
    TAG_ALREADY_EXISTS: 'tag already exists',
    TAG_NAME_REQUIRED: 'tag name is required',
    TAG_TYPE_REQUIRED: 'tag type is required',
    TAG_TYPE_INVALID: 'tag type is invalid',
    TAG_VAL_REQUIRED: 'tag val is required',
};

module.exports = {
    message,
};
